fix: adds check to assert command exists on system

diff --git a/extensions/vscode/justfile b/extensions/vscode/justfile
--- a/extensions/vscode/justfile
+++ b/extensions/vscode/justfile
@@ -32,6 +32,19 @@ assert-binary-executable-exists:
         exit 1
     fi
 
+assert-command-installed command:
+    #!/usr/bin/env bash
+    set -eou pipefail
+    {{ _with_debug }}
+
+    echo "info: checking if {{ command }} is installed..." 1>&2
+    if ! command -v {{ command }} &> /dev/null
+    then
+        echo "error: {{ command }} is not installed..." 1>&2
+        echo "error: please install the binary {{ command }} before proceeding..." 1>&2
+        exit 1
+    fi
+
 # Deletes ephemeral project files (i.e., cleans the project).
 clean:
     #!/usr/bin/env bash
@@ -74,6 +87,8 @@ install os="$(just ../../os)" arch="$(just ../../arch)" editor="code":
     #!/usr/bin/env bash
     set -eou pipefail
     {{ _with_debug }}
+
+    just assert-command-installed {{ editor }}
 
     package=$(just package-name {{ os }} {{ arch }})
     package_path=$(just package-path)
@@ -185,6 +200,8 @@ uninstall editor="code":
     #!/usr/bin/env bash
     set -eou pipefail
     {{ _with_debug }}
+
+    just assert-command-installed {{ editor }}
 
     echo "info: uninstalling extension using '{{ editor }}'..." 1>&2
     {{ editor }} --uninstall-extension 'posit.publisher' 2>&1 | sed 's/^/debug: /'
